### PR TITLE
Add Helping Out section

### PR DESCRIPTION
**Pull request by terminator356**
Added Helping Out section.
Is it acceptable?

### CODE REVIEW

**Comment by kybos** [comment]
We already have all this in the wiki:

https://github.com/muse-sequencer/muse/wiki/Helping

If the Donations is the important part and it should be made more prominent (which I assume ;-) ), I guess we could add just "Donations" explicitly to the web page top menu and link it to your donations page directly.
Or, if it should be more general, add a Helping (or Contributing) entry to the menu with a link to the wiki page above (it should be one word only if possible, that gives a cleaner UI look).

What do you think?

**Comment by terminator356** [comment]
Sorry, I didn't know it was already in the Wiki.

**Comment by spamatica** [comment]
Sorry, late as usual.

We used to have a direct link on the front page for Helping, right?
It seems it got lost in the update, I'm not against adding it back.
Lots of major projects do this:
https://kde.org/   (donate link in the menu)
https://www.gimp.org/ (donate links in the menu)
https://www.audacityteam.org/ (both a link in the toolbar and text and
button on the page)

The last one isn't bad at all, we could do something similar. Linking to
the Helping page and maybe directly to some donate service.

--
Let me add that my stance on donations is that I currently take no part in
donations as I simply don't think I put enough time into MusE.
Tim has setup a donations link that is visible at least on the Helping
page. He puts in a lot of time so it has been quite ok for me (unless he
starts to make millions ;) ).

We did discuss setting up a donations account for the team at some point,
specifically for the project, but it looked like too much effort. Actually
I would be surprised if the donations are more than for a beer now and then
;)

Anyway, as you are are here Kybos, we are one more now that puts in a lot
of time into the project so we should revisit this subject. Time to setup a
team account maybe?

Den tors 5 mars 2020 kl 19:13 skrev Tim <notifications@github.com>:

**Comment by kybos** [comment]
OK, I added a Donate entry in the main menu (linking to Tim's PayPal page).

**Comment by terminator356** [comment]
Hm, I would rather make it clear that it's just me who accepts. That's what my changes did.
I put an anchor near the bottom with a coding contributions section (a link to pull requests),
 and a small donations blurb just for me. I would not want anyone thinking that it's
 a project campaign, but it's just a small personal line I added.

I looked hard to see if github allows such a link on my personal page, like SF does,
 so that users would be forced to visit my page **first** to be sure of who I am,
 and then decide what to do next. But instead I included a reference to my page,
 as well as the PayPal link, so that they can see who exactly they're supporting.

Sorry, I must have looked several times but I missed the info on the Wiki page.
Thus mistaken, I felt a project should at least have some statement about it
 so users aren't sent on a chase wondering whether the project accepts or not.

Read my PR, if it might make more sense here.
It's a more 'delicate' introduction and less 'brutal' than a direct link at the top ;-)
Or the Wiki info could stand. (But hey, even I missed it...)

Thanks.

**Comment by kybos** [comment]
So an additional Helping entry in the web linked to the corresponding wiki page should to the job? Less "brutal" but makes it more visible and easy to find? You can also easily adjust the wiki page if necessary. I changed the web accordingly, please check.

**Comment by terminator356** [comment]
Hey that looks great to me. Thank you!

**Pull request closed without merging**
