### PR TITLE
New Look Wiki

### PR DESCRIPTION
**Pull request by thoth-amon**
New look wiki added.
Changed wiki link and added extra one on the main page top bar for the Spanish translation.

Hopefully doing this pull request right.

### CODE REVIEW

**Comment by spamatica** [comment]
Hi there! Had a look at the material you created and it looks very usable!
Though I realize now I was a bit naive in giving the go-ahead and didn't think through the implications...

I see it says Wiki but unless I am missing something it isn't that any longer. I mean it cannot easily be edited, right?
I fear if we remove the current Wiki we will make it harder for potential writers to add content to the manual.

So I'm thinking maybe we add a link Documentation or Manual on the index page instead of the Wiki links and create a sub page with links like:
Manual 4.0 (en)
Manual 4.0 (es)
Wiki Manual

What do you think?

**Comment by thoth-amon** [comment]
Everything uses github, so it's essentially all the same in ease of adding extra content and "being a wiki". The main difference is using html instead of markup. For that, I have included a template for adding new pages. There is a single contents page for adding links down the side. The pages are also a straight conversion from mark down (using pandoc), so there are just different tags rather than using any difficult new structure. You could write what you want in markdown, use pandoc to convert to html and copy paste the results in to the page.

I could create a page explaining how to edit it?

The main/only problem with having both is managing info on both at the same time.

**Comment by spamatica** [comment]
Very sorry for not getting back to you. I bit too many things to juggle so I forget :/ 
Haven't really managed to dive into this but I think your suggestion, a few lines on how to edit, would be very beneficial for getting this off the ground.

**Comment by thoth-amon** [comment]
I have created a further page showing how to edit it.

**Comment by spamatica** [comment]
Very sorry for the enormous delay. What can I say, it's mostly just embarassing...

Whatever reservations I had about it not being a wiki, it is clearly much better than the alternative (that nothing happens at all).
It will likely be just a few of us editing anyway so it will work out fine! 

Though much delayed, thanks for taking the time!

**Pull request merged**
